<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>c7b6406e-c11c-4ce4-ae44-ece7f113ba1a</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.19" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.19" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.19" />
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PartyApp.Domain\PartyApp.Domain.csproj" />
    <ProjectReference Include="..\PartyApp.Infrastructure\PartyApp.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Common\Extensions\" />
    <Folder Include="Common\Middleware\" />
    <Folder Include="Common\Results\" />
    <Folder Include="Common\Security\" />
    <Folder Include="Modules\Auth\Requests\" />
    <Folder Include="Modules\Auth\Services\" />
    <Folder Include="Modules\Events\Requests\" />
    <Folder Include="Modules\Events\Services\" />
  </ItemGroup>

</Project>
